# Generated by Django 3.0.5 on 2020-04-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
