# Generated by Django 3.0.5 on 2020-04-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0002_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.CharField(choices=[('year1', 'YEAR 1'), ('year2', 'YEAR 2'), ('year3', 'YEAR 3'), ('year4', 'YEAR 4')], default='Year1', max_length=20),
        ),
    ]
