# Generated by Django 3.0.5 on 2020-04-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0003_post_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=15)),
                ('course_name', models.CharField(max_length=100)),
                ('credit_hour', models.FloatField()),
            ],
        ),
    ]
