# Generated by Django 3.0.5 on 2020-04-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_input', models.CharField(max_length=15)),
                ('class_time', models.CharField(max_length=100)),
            ],
        ),
    ]
