# Generated by Django 3.0.5 on 2020-04-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0007_auto_20200420_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
    ]
