# Generated by Django 3.0.5 on 2020-04-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0009_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[('year1', 'YEAR 1'), ('year2', 'YEAR 2'), ('year3', 'YEAR 3'), ('year4', 'YEAR 4')], max_length=20),
        ),
    ]
