# Generated by Django 3.0.5 on 2020-04-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0010_auto_20200421_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.RemoveField(
            model_name='post',
            name='year',
        ),
        migrations.AddField(
            model_name='course',
            name='kulliya',
            field=models.CharField(choices=[('HS', 'ALLIED HEALTH SCIENCES'), ('KAED', 'ARCHITECTURE'), ('CELPAD', 'CELPAD'), ('COCU', 'COCU'), ('DENTISTRY', 'DENTISTRY'), ('EDUCATION', 'EDUCATION'), ('ENGIN', 'ENGIN'), ('ENMS', 'ENMS'), ('KICT', 'KICT'), ('IRKHS', 'IRKHS'), ('ISLAMICBF', 'ISLAMIC BANKING AND FINANCE'), ('ISTAC', 'ISTAC'), ('KLM', 'KLM'), ('LAWS', 'LAWS'), ('MEDICINE', 'MEDICINE'), ('NURSING', 'NURSING'), ('PHARMACY', 'PHARMACY'), ('SCIENCE', 'SCIENCE')], default='ARCHITECTURE', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='kulliya',
            field=models.CharField(choices=[('HS', 'ALLIED HEALTH SCIENCES'), ('KAED', 'ARCHITECTURE'), ('CELPAD', 'CELPAD'), ('COCU', 'COCU'), ('DENTISTRY', 'DENTISTRY'), ('EDUCATION', 'EDUCATION'), ('ENGIN', 'ENGIN'), ('ENMS', 'ENMS'), ('KICT', 'KICT'), ('IRKHS', 'IRKHS'), ('ISLAMICBF', 'ISLAMIC BANKING AND FINANCE'), ('ISTAC', 'ISTAC'), ('KLM', 'KLM'), ('LAWS', 'LAWS'), ('MEDICINE', 'MEDICINE'), ('NURSING', 'NURSING'), ('PHARMACY', 'PHARMACY'), ('SCIENCE', 'SCIENCE')], default='ARCHITECTURE', max_length=20),
        ),
    ]
