# Generated by Django 3.0.5 on 2020-04-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0011_auto_20200421_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uni_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='kulliya',
            field=models.CharField(choices=[('HS', 'ALLIED HEALTH SCIENCES'), ('KAED', 'ARCHITECTURE'), ('CELPAD', 'CELPAD'), ('COCU', 'COCU'), ('DENTISTRY', 'DENTISTRY'), ('EDUCATION', 'EDUCATION'), ('ENGIN', 'ENGIN'), ('ENMS', 'ENMS'), ('KICT', 'KICT'), ('IRKHS', 'IRKHS'), ('ISLAMICBF', 'ISLAMIC BANKING AND FINANCE'), ('ISTAC', 'ISTAC'), ('KLM', 'KLM'), ('LAWS', 'LAWS'), ('MEDICINE', 'MEDICINE'), ('NURSING', 'NURSING'), ('PHARMACY', 'PHARMACY'), ('SCIENCE', 'SCIENCE')], default='ALLIED HEALTH SCIENCES', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='kulliya',
            field=models.CharField(choices=[('HS', 'ALLIED HEALTH SCIENCES'), ('KAED', 'ARCHITECTURE'), ('CELPAD', 'CELPAD'), ('COCU', 'COCU'), ('DENTISTRY', 'DENTISTRY'), ('EDUCATION', 'EDUCATION'), ('ENGIN', 'ENGIN'), ('ENMS', 'ENMS'), ('KICT', 'KICT'), ('IRKHS', 'IRKHS'), ('ISLAMICBF', 'ISLAMIC BANKING AND FINANCE'), ('ISTAC', 'ISTAC'), ('KLM', 'KLM'), ('LAWS', 'LAWS'), ('MEDICINE', 'MEDICINE'), ('NURSING', 'NURSING'), ('PHARMACY', 'PHARMACY'), ('SCIENCE', 'SCIENCE')], default='ALLIED HEALTH SCIENCES', max_length=20),
        ),
    ]
