# Generated by Django 3.0.5 on 2020-04-21 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0016_auto_20200421_0648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='post',
            name='converted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='selected_lang',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='session_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
