# Generated by Django 3.0.5 on 2020-04-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0018_auto_20200421_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='session_key',
        ),
    ]
