# Generated by Django 3.0.5 on 2020-04-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0020_document_output_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='output_file',
        ),
    ]
