# Generated by Django 3.0.5 on 2020-04-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0022_document_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='unique_id',
            field=models.CharField(editable=False, max_length=11, null=True, unique=True),
        ),
    ]
