# Generated by Django 3.0.5 on 2020-04-22 07:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0023_document_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='kulliya',
            field=models.CharField(choices=[('AHS', 'ALLIED HEALTH SCIENCES'), ('HS', 'HUMAN SCIENCES'), ('KAED', 'ARCHITECTURE'), ('CELPAD', 'CELPAD'), ('COCU', 'COCU'), ('DENTISTRY', 'DENTISTRY'), ('EDUCATION', 'EDUCATION'), ('ENGIN', 'ENGIN'), ('ENMS', 'ENMS'), ('KICT', 'KICT'), ('IRKHS', 'IRKHS'), ('ISLAMICBF', 'ISLAMIC BANKING AND FINANCE'), ('ISTAC', 'ISTAC'), ('KLM', 'KLM'), ('LAWS', 'LAWS'), ('MEDICINE', 'MEDICINE'), ('NURSING', 'NURSING'), ('PHARMACY', 'PHARMACY'), ('SCIENCE', 'SCIENCE')], default='ALLIED HEALTH SCIENCES', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='kulliya',
            field=models.CharField(choices=[('AHS', 'ALLIED HEALTH SCIENCES'), ('HS', 'HUMAN SCIENCES'), ('KAED', 'ARCHITECTURE'), ('CELPAD', 'CELPAD'), ('COCU', 'COCU'), ('DENTISTRY', 'DENTISTRY'), ('EDUCATION', 'EDUCATION'), ('ENGIN', 'ENGIN'), ('ENMS', 'ENMS'), ('KICT', 'KICT'), ('IRKHS', 'IRKHS'), ('ISLAMICBF', 'ISLAMIC BANKING AND FINANCE'), ('ISTAC', 'ISTAC'), ('KLM', 'KLM'), ('LAWS', 'LAWS'), ('MEDICINE', 'MEDICINE'), ('NURSING', 'NURSING'), ('PHARMACY', 'PHARMACY'), ('SCIENCE', 'SCIENCE')], default='ALLIED HEALTH SCIENCES', max_length=20),
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_input', models.CharField(max_length=15)),
                ('time_output', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=2)),
            ],
            options={
                'unique_together': {('time_input',)},
            },
        ),
    ]
