# Generated by Django 3.0.5 on 2020-04-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0024_auto_20200422_0700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
